FROM nvcr.io/nvidia/pytorch:24.03-py3

ENV DEBIAN_FRONTEND noninteractive

##############################################################################
# Pip
##############################################################################
RUN pip install tensorstore \
                zarr

RUN pip install tqdm \
                numpy \
                tiktoken

RUN pip install git+https://github.com/huggingface/transformers
